#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'一个能处理去掉=的base64解码函数'

__author__ = 'Daxia'

import  base64

def safe_base64_decode(s):

    if len(s)  % 4 == 0:
        return  base64.b64decode(s)
    else:
        return  base64.b64decode(s + b'=' * (4 - len(s) % 4))

# 测试:
assert b'abcd' == safe_base64_decode(b'YWJjZA=='), safe_base64_decode('YWJjZA==')
assert b'abcd' == safe_base64_decode(b'YWJjZA'), safe_base64_decode('YWJjZA')
print('ok')
