#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Daxia'

#多线程程序
import time, threading

# 新线程执行的代码:
def loop():
    print('thread %s is running...' % threading.current_thread().name)
    n = 0
    st = time.time()
    while n < 5:
        n = n + 1
        print('thread %s >>> %s' % (threading.current_thread().name, n))
        time.sleep(1)
    print('thread %s ended.' % threading.current_thread().name)
    la = time.time()
    print('%.3f' % (la - st))

print('thread %s is running...' % threading.current_thread().name)
t = threading.Thread(target=loop, name='LoopThread')
t.start()
t.join()
print('thread %s ended.' % threading.current_thread().name)



#单线程程序
def loop():
    n = 0
    st = time.time()
    while n < 5:
        n = n + 1
        time.sleep(1)
    la = time.time()
    print('%.3f' % (la - st))

loop()
