#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'验证码'

__author__ = 'Daxia'

from PIL import Image, ImageDraw, ImageFont, ImageFilter

import random, time

# 随机字母:
def rndChar():
    return chr(random.randint(65, 90))

# 随机颜色1:
def rndColor():
    return (random.randint(64, 255), random.randint(64, 255), random.randint(64, 255))

# 随机颜色2:
def rndColor2():
    return (random.randint(32, 127), random.randint(32, 127), random.randint(32, 127))

#定义一个画出验证码的函数
def set_yzm():
    # 240 x 60:
    width = 60 * 4
    height = 60
    image = Image.new('RGB', (width, height), (255, 255, 255))
    # 创建Font对象:
    font = ImageFont.truetype('arial.ttf', 36)
    # 创建Draw对象:
    draw = ImageDraw.Draw(image)
    # 填充每个像素:
    for x in range(width):
        for y in range(height):
            draw.point((x, y), fill=rndColor())
    # 输出文字:
    yzm = []
    for t in range(4):
        f = rndChar()
        draw.text((60 * t + 10, 10), f, font=font, fill=rndColor2())
        yzm.append(f)
    image.show()
    return yzm
    # 模糊:
    #image = image.filter(ImageFilter.BLUR)

#用户输入验证码
def yz_in():
    print('请输入你看到的验证码（区分大小写）：')
    sr = input()
    return  sr

#验证码的验证
def yz_yz():
    yzm = set_yzm()
    time.sleep(1)
    sr = yz_in()
    for i in range(4):
        if sr[i] != yzm[i]:
            print('验证码输入错误，请重新输入')
            return yz_yz()
    print('验证码正确')

yz_yz()
