#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'服务端（将客户端递交的数据加工并返回）'

__author__ = 'Daxia'

import socket, threading, time

#建立一个加工递交数据函数
def tcplink(sock, addr):
    print('Accept new connection from %s: %s...' % addr)
    sock.send(b'Welcome!')
    while True:
        data = sock.recv(1024)
        time.sleep(1)
        #如果客户端没有递交数据或输入'exit'则break
        if not data or  data.decode('utf-8') == 'exit':
            break
        #服务器加工递交数据并编码为utf-8格式发送回客户端
        sock.send(('Hello, %s!' % data.decode('utf-8')).encode('utf-8'))
    sock.close()
    print('Connection from %s: %s closed.' % addr)

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#设置监听端口
s.bind(('127.0.0.1', 9999))
s.listen(5)
print('Waiting for connecting...')

#一旦有客户端连接，此线程就会一直运行下去
while True:
    #接受一个新连接
    sock, addr = s.accept()
    print(sock, addr)
    #创建新线程来处理TCP连接
    t = threading.Thread(target= tcplink, args= (sock, addr))
    t.start()

