#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Daxia'

import re

#test1
def  is_valid_email(str):
    if re.match(r'^[0-9a-zA-z\.]*@[a-zA-Z]*\.com$', str):
        return True
    else:
        return False

# 测试:
assert is_valid_email('someone@gmail.com')
assert is_valid_email('bill.gates@microsoft.com')
assert not is_valid_email('bob#example.com')
assert not is_valid_email('mr-bob@example.com')
print('ok')

#test2
def name_of_email(str):
    t = re.match(r'^<?([\w\s]*)>?([0-9a-zA-z\.\s]*@[a-zA-Z]+\.org)$', str)
    if t:
        print(t.groups())
        return t.group(1)
    else:
        return False

# 测试:
assert name_of_email('<Tom Paris> tom@voyager.org') == 'Tom Paris'
assert name_of_email('tom@voyager.org') == 'tom'
print('ok')
